"""Add disapproval_reason to Users

Revision ID: 025516d75377
Revises: a046d5c18a78
Create Date: 2024-11-14 15:35:18.759363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025516d75377'
down_revision = 'a046d5c18a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disapproval_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('disapproval_reason')

    # ### end Alembic commands ###
