"""Add delivery image field to Pickup model

Revision ID: 205646a9a9c2
Revises: 12e11cd0ad21
Create Date: 2024-11-10 18:55:51.623966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205646a9a9c2'
down_revision = '12e11cd0ad21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.drop_column('delivery_image')

    # ### end Alembic commands ###
