"""Add total Income for Admin

Revision ID: 3c4196aa4cd2
Revises: 54d148d18441
Create Date: 2024-11-10 23:23:35.158666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4196aa4cd2'
down_revision = '54d148d18441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_admin_income', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('total_admin_income')

    # ### end Alembic commands ###
