"""Add address fields to Courier model

Revision ID: 4070609e0952
Revises: f60a6eacbad7
Create Date: 2024-10-28 17:40:03.186779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4070609e0952'
down_revision = 'f60a6eacbad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('barangay', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.drop_column('region')
        batch_op.drop_column('province')
        batch_op.drop_column('city')
        batch_op.drop_column('barangay')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
