"""Add total Income for seller

Revision ID: 54d148d18441
Revises: 205646a9a9c2
Create Date: 2024-11-10 22:38:51.525620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d148d18441'
down_revision = '205646a9a9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_income', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_column('total_income')

    # ### end Alembic commands ###
