"""Add delivered_at to pickups

Revision ID: 674295223c7b
Revises: 081b6d3cce5b
Create Date: 2024-11-22 18:15:37.481605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674295223c7b'
down_revision = '081b6d3cce5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
