"""Add Pickup model and pickup_orderitem association table

Revision ID: 86d61a106f54
Revises: 96e3593bd57a
Create Date: 2024-10-28 21:16:23.217632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d61a106f54'
down_revision = '96e3593bd57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickup_orderitem',
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ),
    sa.PrimaryKeyConstraint('pickup_id', 'order_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickup_orderitem')
    op.drop_table('pickups')
    # ### end Alembic commands ###
