"""Add total shipping for Admin

Revision ID: 8c771c6d6cb9
Revises: 3c4196aa4cd2
Create Date: 2024-11-10 23:51:29.048853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c771c6d6cb9'
down_revision = '3c4196aa4cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_shipping_income', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('total_shipping_income')

    # ### end Alembic commands ###
