"""Add Contact Number

Revision ID: 96e3593bd57a
Revises: 4070609e0952
Create Date: 2024-10-28 18:17:40.330968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e3593bd57a'
down_revision = '4070609e0952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
