"""add courier income

Revision ID: a89604273a2e
Revises: 19e76861188d
Create Date: 2024-11-28 21:02:51.652566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89604273a2e'
down_revision = '19e76861188d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_shipping_income', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.drop_column('total_shipping_income')

    # ### end Alembic commands ###
