"""Add image review

Revision ID: c16343b0fe82
Revises: aaceb1a04988
Create Date: 2024-11-18 19:20:14.317254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16343b0fe82'
down_revision = 'aaceb1a04988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('helpfulness')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('helpfulness', sa.INTEGER(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
