"""Added cancel reason to OrderItem

Revision ID: c2a147a05e0e
Revises: 86d61a106f54
Create Date: 2024-10-31 13:16:29.745489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a147a05e0e'
down_revision = '86d61a106f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('cancel_reason')

    # ### end Alembic commands ###
