"""New migration after correction

Revision ID: f60a6eacbad7
Revises: 
Create Date: 2024-10-28 00:23:50.272018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60a6eacbad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickup_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('courier_id', sa.INTEGER(), nullable=True),
    sa.Column('pickup_date', sa.DATE(), nullable=False),
    sa.Column('pickup_time', sa.TIME(), nullable=False),
    sa.Column('pickup_location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pickup_status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
